// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
//
// IMPORTANT: `supabase.auth.getSession()` returns the CACHED session and does
// NOT refresh an expired access_token. supabase-js only auto-refreshes on its
// own timer / visibilitychange, so RPCs fired before that tick go out with a
// stale JWT and PostgREST rejects them with PGRST301 ("JWT expired"). We
// proactively refresh here when the token is expired (or within a small skew
// window) so every serverFn call carries a valid bearer.
const EXPIRY_SKEW_SECONDS = 30

export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    let session = (await supabase.auth.getSession()).data.session
    if (session?.expires_at) {
      const nowSec = Math.floor(Date.now() / 1000)
      if (session.expires_at - EXPIRY_SKEW_SECONDS <= nowSec) {
        const refreshed = await supabase.auth.refreshSession()
        if (!refreshed.error && refreshed.data.session) {
          session = refreshed.data.session
        }
      }
    }
    const token = session?.access_token
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
